#!/usr/bin/env python3

'''
A simple quantum circuit that replicates the state of a qubit to N others

Copyright (C) 2020 Cody Lewis

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''

import argparse

from qiskit import QuantumCircuit, Aer, execute

def to_statevector(a):
    '''Convert a binary string into its representative qubit statevector'''
    if a == "0":
        return [1, 0]
    return [0, 1]

def create_circuit(in_state, n):
    '''Construct the circuit with the input states set'''
    qcircuit = QuantumCircuit(n)
    qcircuit.initialize(to_statevector(in_state[0]), 0)
    for i in range(1, n):
        qcircuit.cnot(0, i)
    meas = QuantumCircuit(n, n)
    meas.barrier(range(n))
    meas.measure(range(n), range(n))
    return qcircuit + meas


if __name__ == '__main__':
    print(
        "swap  Copyright (C) 2020  Cody Lewis\n" +
        "This program comes with ABSOLUTELY NO WARRANTY.\n" +
        "This is free software, and you are welcome to redistribute it under certain conditions.\n"
    )
    PARSER = argparse.ArgumentParser(
        description="A simple quantum circuit that replicates the state of a qubit to N others"
    )
    PARSER.add_argument(
        'in_state', metavar='INPUT_STATE', type=str,
        help='Binary string representing the input state of the qubit'
    )
    PARSER.add_argument(
        'n', metavar='N', type=int,
        help='The number of qubits to fanout to'
    )
    ARGS = PARSER.parse_args()
    QCIRC = create_circuit(ARGS.in_state, ARGS.n)
    print("Created circuit:")
    print(QCIRC.draw())
    BACKEND_SIM = Aer.get_backend('qasm_simulator')
    RESULT = execute(QCIRC, BACKEND_SIM).result()
    print(f'Result: |{ARGS.in_state}> -> |{max(RESULT.get_counts())[::-1]}>')
